org: andersonalex666
app: elegant-weather
service: elegant-weather-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

custom:
  functionsBasePath: src/handlers
  serverless-offline:
    printOutput: true

functions:
  api:
    handler: forecast.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  - serverless-functions-base-path